### ISSUE TITLE
deleting this repo

### ISSUE THREAD

**Issue by pierluca** [cvra/pid-config#2]
Hi,

Is anyone against the deletion of this repo? It's superseded at this point, there's no reason to keep it around.

Cheers,

Pierluca

**Comment by froj** [comment]
Why delete it? It's not like we have limitation of the number of repos we host on github.

**Comment by pierluca** [comment]
Why keep it? :-) it doesn't provide anything useful, not even history. In that sense, its existence brings 0 value to CVRA.

Also, I have a vested interested. A local configuration mistake points to my surname in a commit, which I'm not too happy about. (self-face-palm)

**Comment by froj** [comment]
ah I didn't realize it was empty. yeah go ahead and delete it.
